=== chrissimpkins/codeface/data/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Font Metadata Schema",
	"type": "object",
	"properties": {
		"name":    { "type": "string" },
		"author":  { "type": "string" },
		"license": { "type": "string" },
		"year":    { "type": "integer", "minimum": 0 },
		"serif":   { "type": "boolean" },
		"free":    { "enum": [ "open license", "commercial", "free for personal use" ] },
		"websites": {
			"type": "array",
			"items": { "type": "string" },
			"minItems": 1,
			"uniqueItems": true
		},
		"tags": {
			"type": "array",
			"items": { "type": "string" },
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": [
		"name",
		"author",
		"license",
		"free",
		"serif"
	],
	"additionalProperties" : false
}

=== chrissimpkins/codeface/data/liberation-mono/data.json
{
	"name": "Liberation Mono",
	"author": "Steve Matteson",
	"year": 2007,
	"license": "Red Hat Liberation License",
	"websites": [
		"https://fedorahosted.org/liberation-fonts/",
		"http://www.fontsquirrel.com/fonts/Liberation-Mono"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/latin-modern-mono/data.json
{
	"name": "Latin Modern Mono",
	"author": "Bogusław Jackowski, Janusz M. Nowacki",
	"year": 2002,
	"license": "GUST Font License",
	"websites": [
		"http://www.gust.org.pl/gust/projects/e-foundry/latin-modern",
		"http://www.fontsquirrel.com/fonts/Latin-Modern-Mono"
	],
	"serif": true,
	"free": "open license",
	"tags": [
		"latex",
		"gust"
	]
}

=== chrissimpkins/codeface/data/cousine/data.json
{
	"name": "Cousine",
	"author": "Steve Matteson",
	"year": 2010,
	"license": "Apache",
	"websites": [
		"http://www.fontsquirrel.com/fonts/cousine",
		"http://www.google.com/fonts/specimen/Cousine"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"courier",
		"professional",
		"free"
	]
}

=== chrissimpkins/codeface/data/pt-mono/data.json
{
	"name": "PT Mono",
	"author": "Alexandra Korolkova, Isabella Chaeva",
	"year": 2011,
	"license": "SIL OFL",
	"websites": [
		"http://paratype.com/public/",
		"http://www.fontsquirrel.com/fonts/pt-mono",
		"http://www.google.com/fonts/specimen/PT+Mono"
	],
	"serif": true,
	"free": "open license",
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/tex-gyre-cursor/data.json
{
	"name": "TeX Gyre Cursor",
	"author": "GUST e-foundry",
	"year": 2006,
	"license": "LPPL",
	"websites": [
		"http://www.gust.org.pl/projects/e-foundry/tex-gyre",
		"http://www.fontsquirrel.com/fonts/TeX-Gyre-Cursor"
	],
	"serif": true,
	"free": "open license",
	"tags": [
		"gust",
		"nimbus"
	]
}

=== chrissimpkins/codeface/data/not-courier-sans/data.json
{
	"name": "NotCourierSans",
	"author": "Open Source Publishing",
	"year": 2008,
	"license": "SIL OFL",
	"websites": [
		"http://www.fontsquirrel.com/fonts/NotCourierSans",
		"http://openfontlibrary.org/en/font/notcouriersans"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"nimbus"
	]
}

=== chrissimpkins/codeface/data/source-code-pro/data.json
{
	"name": "Source Code Pro",
	"author": "Paul D. Hunt",
	"year": 2012,
	"license": "SIL OFL",
	"websites": [
		"https://github.com/adobe-fonts/source-sans-pro",
		"http://blog.typekit.com/2012/09/24/source-code-pro/",
		"http://www.fontsquirrel.com/fonts/source-code-pro",
		"http://www.google.com/fonts/specimen/Source+Code+Pro"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"professional",
		"open source",
		"github"
	]
}

=== chrissimpkins/codeface/data/fantasque-sans-mono/data.json
{
	"name": "Fantasque Sans Mono",
	"author": "Jany Belluz",
	"year": 2013,
	"license": "SIL OFL",
	"websites": [
		"http://openfontlibrary.org/en/font/fantasque-sans-mono",
		"https://github.com/belluzj/fantasque-sans"
	],
	"serif": false,
	"free": "open license",
	"tags": [
		"github",
		"open source"
	]
}
