=== chrissimpkins/codeface/data/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Font Metadata Schema",
	"type": "object",
	"properties": {
		"name":    { "type": "string" },
		"author":  { "type": "string" },
		"license": { "type": "string" },
		"year":    { "type": "integer", "minimum": 0 },
		"serif":   { "type": "boolean" },
		"free":    { "enum": [ "open license", "commercial", "free for personal use" ] },
		"websites": {
			"type": "array",
			"items": { "type": "string" },
			"minItems": 1,
			"uniqueItems": true
		},
		"tags": {
			"type": "array",
			"items": { "type": "string" },
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": [
		"name",
		"author",
		"license",
		"free",
		"serif"
	],
	"additionalProperties" : false
}

=== chrissimpkins/codeface/data/sharetech-mono/data.json
{
	"name": "Share Tech Mono",
	"author": "Ralph du Carrois",
	"year": 2012,
	"license": "SIL OFL",
	"websites": [
		"http://www.google.com/fonts/specimen/Share+Tech+Mono",
		"http://www.fontsquirrel.com/fonts/Share-Regular"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/inconsolata/data.json
{
	"name": "Inconsolata",
	"author": "Raph Levien",
	"year": 2001,
	"license": "SIL OFL",
	"websites": [
		"http://www.levien.com/type/myfonts/inconsolata.html",
		"http://www.google.com/fonts/specimen/Inconsolata",
		"http://www.fontsquirrel.com/fonts/Inconsolata"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"consolas"
	]
}

=== chrissimpkins/codeface/data/audimat-mono/data.json
{
	"name": "Audimat Mono",
	"author": "SMeltery",
	"year": 2008,
	"license": "requires permission",
	"websites": [
		"http://www.fontsquirrel.com/fonts/Audimat-Mono",
		"http://www.smeltery.net/fonts/audimat-mono"
	],
	"free": "free for personal use",
	"serif": false,
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/ubuntu-mono/data.json
{
	"name": "Ubuntu Mono",
	"author": "Dalton Maag",
	"year": 2010,
	"license": "Ubuntu/SIL OFL",
	"websites": [
		"http://font.ubuntu.com",
		"http://www.fontsquirrel.com/fonts/ubuntu-mono",
		"http://www.google.com/fonts/specimen/Ubuntu+Mono"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/fira-mono/data.json
{
	"name": "Fira Mono",
	"author": "Erik Spiekerman, Carois Type Design",
	"year": 2013,
	"license": "SIL OFL",
	"websites": [
		"https://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/",
		"http://www.fontsquirrel.com/fonts/fira-mono",
		"http://www.google.com/fonts/specimen/Fira+Mono"
	],
	"free": "open license",
	"serif": false,
	"tags": [
		"professional"
	]
}

=== chrissimpkins/codeface/data/cutive-mono/data.json
{
	"name": "Cutive Mono",
	"author": "Vernon Adams",
	"year": 2012,
	"license": "SIL OFL",
	"websites": [
		"http://www.google.com/fonts/specimen/Cutive+Mono",
		"https://github.com/vernnobile/CutiveFont",
		"http://luc.devroye.org/fonts-47641.html"
	],
	"serif": true,
	"free": "open license",
	"tags": [
		"typewriter",
		"github",
		"open source",
		"professional"
	]
}

=== chrissimpkins/codeface/data/anonymous-pro/data.json
{
	"name": "Anonymous Pro",
	"author": "Mark Simonson",
	"year": 2009,
	"license": "SIL OFL",
	"websites": [
		"http://www.marksimonson.com/fonts/view/anonymous-pro",
		"http://www.fontsquirrel.com/fonts/Anonymous-Pro",
		"http://www.google.com/fonts/specimen/Anonymous+Pro"
	],
	"serif": false,
	"free": "open license",
	"tags": [
		"professional"
	]
}
